### ISSUE TITLE
The transaction auto commits if any timeout

### ISSUE THREAD

**Issue by nagavenkatab** [BesLogic/sails-mysql-atomic#32]
I am using the below code to test transaction user_details model, I have put time out of 2 sec. the transaction is auto-committing and throws an error as "This transaction has already been committed
"
` SqlHelper.beginTransaction(transaction => {
                return transaction.forModel(sails.models['user_details']).update(reqObj, reqBody).then((dat) => {
                    console.log("dat", dat)
                    setTimeout(() => {
                        transaction.commit().then((rb) => {
                            console.log("rb", rb)
                            return res.json(dat);
                        }).catch((err5) => {
                            console.log("err5", err5) // here it throws error
                        })
                    
                    }, 2000);

                }).catch((err4) => {
                    console.log("err4", err4)
                })
            });
`

**Comment by sam9291** [comment]
Hi @nagavenkatab,

It happens because your promise chain for the transaction goes out of sync because of the timeout. If you want to use a timeout, you must manually sync the promise chain. Here's how I would do:

```
const Promise = require('bluebird');

SqlHelper.beginTransaction(transaction => {
    return transaction.forModel(sails.models['user_details']).update(reqObj, reqBody).then((dat) => {
        console.log("dat", dat)

        return new Promise((resolve, reject) => {
            setTimeout(() => {
                transaction.commit().then((rb) => {
                    console.log("rb", rb)
                    resolve(dat); // Resolve the promise here to keep the promise chain in sync for the transaction
                }).catch((err5) => {
                    console.log("err5", err5)
                })
    
            }, 2000);
        })
        

    }).catch((err4) => {
        console.log("err4", err4)
    })
})
.then(dat => res.json(dat)); // This will run after the transaction commit
```

**Comment by samuel-poirier** [comment]
I've added a test to ensure that this scenario is covered:

[Timeout test](https://github.com/BesLogic/sails-mysql-atomic/commit/fe0ada6c6a650137b18caa497934aa398f56a8b3#diff-7433913c69e2dda2887b5a98673d083aR897)

**Comment by nagavenkatab** [comment]
@sam9291 Thanks for the quick help and thank you so much for the wonderful module.
is it on top of sails-mysql-transactions? with 0.8.4-hotfix.4 version I have an issue. The rollback is not working which is similar to https://github.com/postmanlabs/sails-mysql-transactions/issues/61

**Comment by samuel-poirier** [comment]
It initially was on top of sails-mysql-transactions, but because of that issue, I decided to do a complete rework from release 1.1.2 to fix this:

https://github.com/BesLogic/sails-mysql-atomic/releases/tag/1.1.2

You still have the rollback issue using sails-mysql-atomic?

**Comment by nagavenkatab** [comment]
no, with sails-mysql-atomic everything is working fine. I had the rollback issue with sails-mysql-transactions only.

**Comment by samuel-poirier** [comment]
Ah, then you went through the same blocker issue I encountered last year my friend :)

We've been using our plugin in production for a while now and never saw any issue since we did the switch.
