### ISSUE TITLE
db entry create with transaction doesn't rollback

### ISSUE THREAD

**Issue by venkatbokka** [BesLogic/sails-mysql-atomic#36]
I am using the below code to manually rollback the create entry, but the entry is getting created in db even if I do rollback, can you please let me know if I am missing something.

```
export function create(gridObj: any, gridVersionObj: any) {
    return sqlHelper.beginTransaction(transaction => {
        return transaction.forModel(sails.models['grid']).create(gridObj).then((gridData) => {
            return transaction.rollback();
        }).catch((err) => {
            return transaction.rollback(err);
        });
    });
}
```

**Comment by samuel-poirier** [comment]
I haven't tested the adapter in typescript, I can't confirm if it works as in javascript. From what I see in your code, it looks fine. You are using `adapter: 'sails-mysql-atomic'` as your connection adapter?

**Comment by venkatbokka** [comment]
That's my mistake I am using sails-mysql instead of sails-mysql-atomic, after change it works well.
Thank you.
and it works in typescript as well.
